org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21,)
loader_version_range=[2,)
mod_id=maidmoreanimation
mod_name=moreanimation
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.github.tartaricacid
mod_authors=
mod_description=
geckolib_version=4.4.2
touhou_little_maid_version=1.5.3-neoforge+mc1.21.1
