modLoader = "javafml"
loaderVersion = "[2,)"
license = "All rights reserved"

[[mods]]
modId = "maidmoreanimation"
version = "1.0.0"
displayName = "More Animation"
authors = "JumDa5he"
description = "More maid animations: hug, tail pull and more."

[[mixins]]
config = "mixins.maidmoreanimation.json"

[[dependencies."maidmoreanimation"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."maidmoreanimation"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
